#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II III
bspc monitor DP-4 -d IV V VI
bspc monitor HDMI-0 -d VII VIII IX

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

polybar &
picom &
feh --bg-fill Pictures/duel.png --bg-fill Pictures/crocodile1.png --bg-fill Pictures/flower.png &
xrandr --output DP-4 --primary --mode 3840x2160  --output DP-0 --mode 1920x1080 --rotate right --left-of DP-4 --output HDMI-0 --mode 1920x1080 --rotate normal --right-of DP-4
